Base Template
HorizonsEndMC/Wiki pull request #2
Opened 2022-01-27 21:13 UTC by Ashparty

Worked a ton on my repo, a lot of information is missing but i thought it would be good to get the base for the wiki down on the main repository.

2022-01-27 21:19 UTC, Ashparty commented
Also, if this PR gets accepted i'll keep working on my repo and will make more PR's once a significant portion has been completed.

2022-01-27 21:19 UTC, Peter-Crawley requested changes

2022-01-27 21:19 UTC, Peter-Crawley commented on README.md
> +# Editor/Dev Usage
CONTRIBUTING.md

2022-01-27 21:19 UTC, Peter-Crawley commented on Space/Space-Wiki.code-workspace
> +{
.gitignore this please.

2022-01-27 21:19 UTC, Peter-Crawley commented on Space/Planets/Base (Edit)
> +.
What is this for?

2022-01-27 21:19 UTC, Peter-Crawley commented on Starships/Entrances.md
> +# Boarding Ramps
Add a warning that they are broken.

2022-01-27 21:19 UTC, Peter-Crawley commented on Starships/Thrusters.md
> +NOTE: INFORMATION ON THIS PAGE MAY BE OUTDATED
Remove glowstone and this warning.

2022-01-27 21:19 UTC, Peter-Crawley commented on Starships/Weapons.md
> +# Rockets? (Needs verification)
May end up being removed for launch.

2022-01-27 21:19 UTC, Peter-Crawley commented on Starships/Weapons.md
> +# Phasers? (Needs verification)
Yes

2022-01-27 21:19 UTC, Peter-Crawley commented on Starships/Weapons.md
> +Also see the machines section for turrets
Link

2022-01-27 21:22 UTC, Ashparty commented on Space/Space-Wiki.code-workspace
> +{
Will do once i get back to a computer.

2022-01-27 21:30 UTC, Ashparty commented on README.md
> +# Editor/Dev Usage
Fixed

2022-01-27 21:31 UTC, Ashparty commented on Space/Planets/Base (Edit)
> +.
Just had to put a file in because i was using JUST github, not sure what planets there are so i just put in a placeholder file

2022-01-27 21:33 UTC, Peter-Crawley commented on Space/Planets/Base (Edit)
> +.
But why is there a `.`?

2022-01-27 21:34 UTC, Ashparty commented on Space/Planets/Base (Edit)
> +.
It needed to be filled with something, i probably should have just put {placeholder}

2022-01-27 21:44 UTC, Ashparty commented on Starships/Weapons.md
> +# Rockets? (Needs verification)
Removed the rockets area, i'll re-add it if they stay on launch

2022-01-27 21:45 UTC, Ashparty commented on Starships/Weapons.md
> +# Phasers? (Needs verification)
Fixed

2022-01-27 22:57 UTC, Ashparty commented on Starships/Weapons.md
> +Also see the machines section for turrets
Just removed it for now because stuff didnt work, i'll re-add it later when i make my next PR

2022-01-28 02:31 UTC, Ashparty commented on Starships/Entrances.md
> +# Boarding Ramps
Done

2022-01-28 03:09 UTC, Ashparty commented
The starship information is **MOSTLY** Done

2022-01-29 02:38 UTC, Ashparty commented
All the changes you have requested should be done now 👍

2022-01-29 14:23 UTC, Peter-Crawley approved these changes

2022-01-29 14:26 UTC, Peter-Crawley commented
*rebase merging is prefered, makes a cleaner commit history.*

2022-01-29 14:27 UTC, merged